if [ ! $# -eq 1 ] ; then
    echo "Usage: $0 new_env_name";
    exit 1
fi

env_name=$1
env_name_file="envname.txt"

if [ -f $env_name_file ] ; then
    last_env_name=$(cat $env_name_file|tr -d '\n')
    sed -i "s/int main/int main_""$last_env_name""/g" main.cpp
    mv main.cpp "solution_""$last_env_name"".cpp"
fi

echo "$env_name">$env_name_file
rm -f main.cpp
{
    echo "// generated by $(whoami) at $(date)"
    echo "#include <iostream>"
    echo '#include "dataloader.h"'
    echo ''
    echo 'int main() {'
    echo '    SolutionTester ST;'
    echo '    // add test case here'
    echo '    '
    echo '    // set check function'
    echo '    ST.setCheckFn([] (DataLoader& DL) -> bool {'
    echo '        '
    echo '        return true;'
    echo '    });'
    echo '    ST.test();'
    echo '}'
}>main.cpp
